version = "2"
Vagrant.configure(version) do |config|
  config.vm.box = "bento/centos-6.7"

  config.vm.define :teacher do | teacher |
    teacher.vm.hostname = "teacher"
    teacher.vm.network "forwarded_port", guest: 80, host: 8080
    teacher.vm.network "forwarded_port", guest: 8080, host: 8081
    teacher.vm.network "forwarded_port", guest: 5000, host: 5001
    teacher.vm.network "forwarded_port", guest: 27017, host: 27018
    teacher.vm.network "forwarded_port", guest: 29418, host: 29419
    #teacher.vm.network :public_network, :auto_config => false
    #teacher.vm.provision :shell, :path => "public_ip_setting.sh"
    teacher.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)"
    teacher.vm.network "private_network", ip: "192.168.33.10", virtualbox__intnet: "net1"
    teacher.vm.synced_folder "src/teacher", "/src", owner: "vagrant", group: "vagrant"
    #teacher.vm.provision "shell", path: "teacher_init.sh"
    teacher.ssh.private_key_path = "~/.ssh/id_rsa"
  end

  config.vm.define :student00 do | student00 |
    student00.vm.hostname = "student00"
    student00.vm.network "private_network", ip: "192.168.33.20", virtualbox__intnet: "net1"
    student00.vm.synced_folder "src/student", "/src", owner: "vagrant", group: "vagrant"
    #student00.vm.provision "shell", path: "student_init.sh"
    student00.ssh.private_key_path = "~/.ssh/id_rsa"
  end
end
