version: "3"
services:
  logger_server:
    build: logger_server/.
    image: logger_server
    hostname: logger_server
    container_name: logger_server
    tty: true
    privileged: true
    networks:
      - logger-collect-network
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
  collect_server:
    build: collect_server/.
    image: collect_server
    hostname: collect_server
    container_name: collect_server
    tty: true
    privileged: true
    volumes:
      - ./collect_server/log_collect/:/root/log_collect
      - ./collect_server/model/:/root/model
      - ./collect_server/web/:/root/web
    networks:
      - logger-collect-network
    ports:
      - "23:22"
      - "5000:5000"
  httpd:
    image: httpd
    restart: always
    hostname: httpd
    container_name: httpd
    volumes:
      - ./web/Viewer/Visualize:/usr/local/apache2/htdocs/
    networks:
      - logger-collect-network
    ports:
      - "81:80"
  mongo:
    image: mongo
    restart: always
    hostname: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
      - 27018:27018
    volumes:
      - ./mongodb/db:/data/db
      # - ./logs/mongo_db/configdb:/data/configdb
    networks:
      - logger-collect-network
  mongo-express:
    image: mongo-express
    hostname: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - logger-collect-network

networks:
  logger-collect-network:
    external: true
