version: "3"
services:
  logger_server001:
    build: logger_server/.
    image: logger_server
    hostname: logger_server001
    container_name: logger_server001
    tty: true
    privileged: true
    networks:
      - logger-collect-network
    ports:
      - "2201:22"
      - "8001:80"
      - "44301:443"
  logger_server002:
    build: logger_server/.
    image: logger_server
    hostname: logger_server002
    container_name: logger_server002
    tty: true
    privileged: true
    networks:
      - logger-collect-network
    ports:
      - "2202:22"
      - "8002:80"
      - "44302:443"
  logger_server003:
    build: logger_server/.
    image: logger_server
    hostname: logger_server003
    container_name: logger_server003
    tty: true
    privileged: true
    networks:
      - logger-collect-network
    ports:
      - "2203:22"
      - "8003:80"
      - "44303:443"
  collect_server:
    build: collect_server/.
    image: collect_server
    hostname: collect_server
    container_name: collect_server
    tty: true
    privileged: true
    volumes:
      - ./collect_server/log_collect/:/root/log_collect
      - ./collect_server/model/:/root/model
      - ./collect_server/web/:/root/web
      - ./collect_server/web2/:/root/web2
    networks:
      - logger-collect-network
    ports:
      - "23:22"
      - "5001:5000"
      - "81:80"
  mongo:
    image: mongo
    restart: always
    hostname: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
      - 27018:27018
    volumes:
      - ./mongodb/db:/data/db
      # - ./logs/mongo_db/configdb:/data/configdb
    networks:
      - logger-collect-network
  mongo-express:
    image: mongo-express
    hostname: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - logger-collect-network
  gitbucket:
    image: gitbucket/gitbucket
    hostname: gitbucket
    container_name: gitbucket
    restart: always
    ports:
      - 8080:8080
      - 29418:29418
    volumes:
      - ./logs/gitbucket:/gitbucket
    environment:
      - GITBUCKET_DB_USER=gitbucket
      - GITBUCKET_DB_PASSWORD=gitbucket
    command:
      ["sh", "-c", "java -jar /opt/gitbucket.war --max_file_size=3145728"]
    networks:
      - logger-collect-network

networks:
  logger-collect-network:
    external: true
