version: "3"
services:
  logger_server:
    build: logger_server/.
    image: logger_server
    hostname: logger_server
    container_name: logger_server
    tty: true
    privileged: true
    networks:
      - logger-collect-network
    ports:
      - "22001:22"
      - "8081:80"
      - "44003:443"
  collect_server:
    build: collect_server/.
    image: collect_server
    hostname: collect_server
    container_name: collect_server
    tty: true
    privileged: true
    volumes:
      - ./collect_server/log_collect/:/root/log_collect
      - ./collect_server/model/:/root/model
      - ./collect_server/web/:/root/web
    networks:
      - logger-collect-network
    ports:
      - "22002:22"
      - "5001:5000"
  mongo:
    image: mongo
    restart: always
    hostname: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./logs/mongo_db:/data/db
    networks:
      - logger-collect-network
    ports:
      - "27017:27017"
  httpd:
    image: httpd
    restart: always
    hostname: httpd
    container_name: httpd
    volumes:
      - ./web/Viewer/Visualize:/usr/local/apache2/htdocs/
    networks:
      - logger-collect-network
    ports:
      - "8082:80"

networks:
  logger-collect-network:
    external: true
